*---------------------------------------------------------------------------------------
SUBROUTINE E.SCB.NOFILE.SC.BLK.SEC.POS.ID(Y.ARRAY)
*---------------------------------------------------------------------------------------
* 30-10-2025 - 1543890 - 8658135 - Nofile routine attached to ENQUIRY>SCB.E.BLK.UNBLK.RECORDS
* NoFileEnquiry routine to view all the Blocks or Unblocks created (either automatically or manually)
* for the day in question and it should display all the fields that are updated in the Block/Unblock records.
* 29th May 2026 - Krithika - 12911722- EQD - Request to add CIF in the “Display EQD Block/Unblock Records” menu
*---------------------------------------------------------------------------------------

$INSERT I_COMMON
$INSERT I_EQUATE
$INSERT I_ENQUIRY.COMMON
$INSERT I_F.SC.BLOCK.SEC.POS

GOSUB INIT
GOSUB PROCESS

RETURN

INIT:
*****

    Y.POS = ''; Y.EFF.DATE = ''; Y.SC.BLK.SEC.POS = ''; Y.SC.BLK.CNT = ''; Y.SC.BLK.ERR = ''; Y.HIS.FLAG = ''; Y.ARRAY = ''
	Y.L.BLK.TYPE.POS = ''; Y.OPT.SM.ID.POS = ''; Y.LWM.SECTR.ID.POS = ''; Y.POS = ''; Y.SEL.CMD = ''; Y.SEL.CMD.HIS = ''
    
    Y.APPL = 'SC.BLOCK.SEC.POS'
    Y.FLD.NAMES  = 'L.BLOCK.TYPE':@VM:'L.OPTION.SM.ID':@VM:'LWM.SECTR.ID'
    Y.FLD.POS = ''
    CALL MULTI.GET.LOC.REF(Y.APPL,Y.FLD.NAMES,Y.FLD.POS)
	
    Y.L.BLK.TYPE.POS = Y.FLD.POS<1,1>
    Y.OPT.SM.ID.POS = Y.FLD.POS<1,2>
    Y.LWM.SECTR.ID.POS = Y.FLD.POS<1,3>
    
    FN.SC.BLOCK.SEC.POS = 'F.SC.BLOCK.SEC.POS'
    F.SC.BLOCK.SEC.POS = ''
    CALL OPF(FN.SC.BLOCK.SEC.POS,F.SC.BLOCK.SEC.POS)
    
    FN.SC.BLOCK.SEC.POS.HIS = 'F.SC.BLOCK.SEC.POS$HIS'
    F.SC.BLOCK.SEC.POS.HIS = ''
    CALL OPF(FN.SC.BLOCK.SEC.POS.HIS,F.SC.BLOCK.SEC.POS.HIS)

    LOCATE 'EFF.FROM.DATE' IN D.FIELDS<1> SETTING Y.POS THEN
        Y.EFF.DATE = D.RANGE.AND.VALUE<Y.POS>		
    END
	
RETURN


PROCESS:
********

    Y.SC.BLK.SEC.POS = ''; Y.SC.BLK.CNT = ''; Y.SC.BLK.ERR = ''; Y.SEL.CMD.HIS = ''; Y.SC.BLK.HIS.ERR = ''

	IF Y.EFF.DATE THEN
	
	   Y.SEL.CMD = 'SELECT ':FN.SC.BLOCK.SEC.POS:' WITH L.OPTION.SM.ID NE "" AND EFF.FROM.DATE EQ ':Y.EFF.DATE
	   CALL EB.READLIST(Y.SEL.CMD,Y.SC.BLK.SEC.POS,'',Y.SC.BLK.CNT,Y.SC.BLK.ERR)
	   IF NOT(Y.SC.BLK.SEC.POS) THEN
	      Y.SC.BLK.SEC.POS = ''; Y.SC.BLK.CNT = ''; Y.SC.BLK.ERR = ''
	      Y.SEL.CMD.HIS = 'SELECT ':FN.SC.BLOCK.SEC.POS.HIS:' WITH L.OPTION.SM.ID NE "" AND EFF.FROM.DATE EQ ':Y.EFF.DATE
		  CALL EB.READLIST(Y.SEL.CMD.HIS,Y.SC.BLK.SEC.POS,'',Y.SC.BLK.CNT,Y.SC.BLK.HIS.ERR)
		  Y.HIS.FLAG = 1
	   END
	   
	   Y.BLK.POS = ''; Y.TXN.TYPE = ''; Y.BLOCK.TYPE = ''; Y.SM.CODE = ''; Y.SEC.DEPO = ''; Y.OPT.SM.ID = ''; Y.CURR.AMT.BLOCKED = ''
	   Y.NEW.AMT.BLOCKED = ''; Y.EFF.FROM.DATE = ''; Y.BLOCKED.UNTIL = ''; Y.EFF.TO.DATE = ''; Y.ADDITION.INFO = ''
	   Y.LWM.SECTR.ID = ''; Y.RECORD.STATUS = ''; Y.INPUTTER = ''; Y.AUTHORISER = ''; Y.DATE.TIME = ''; Y.SC.BLK.SEC.POS.IDX = ''
	   *Y.SC.BLK.SEC.POS = 'BBLKSC2503400194':@FM:'BBLKSC2503400209'
	   LOOP
	   REMOVE Y.SC.BLK.SEC.POS.ID FROM Y.SC.BLK.SEC.POS SETTING Y.BLK.POS
	   WHILE Y.SC.BLK.SEC.POS.ID:Y.BLK.POS
	   
	      IF Y.HIS.FLAG THEN
	        R.SC.BLOCK.SEC.POS = ''; Y.SC.BLOCK.SEC.HIS.ERR = ''
			Y.SC.BLK.SEC.POS.ID = FIELD(Y.SC.BLK.SEC.POS.ID,';',1)
	        CALL F.READ.HISTORY(FN.SC.BLOCK.SEC.POS.HIS,Y.SC.BLK.SEC.POS.ID,R.SC.BLOCK.SEC.POS,F.SC.BLOCK.SEC.POS.HIS,Y.SC.BLOCK.SEC.HIS.ERR)
	      END ELSE
	        R.SC.BLOCK.SEC.POS = ''; Y.SC.BLOCK.SEC.POS.ERR = ''
	        CALL F.READ(FN.SC.BLOCK.SEC.POS,Y.SC.BLK.SEC.POS.ID,R.SC.BLOCK.SEC.POS,F.SC.BLOCK.SEC.POS,Y.SC.BLOCK.SEC.POS.ERR)
	      END
	      
		  Y.BLK.POS = ''; Y.TXN.TYPE = ''; Y.BLOCK.TYPE = ''; Y.SM.CODE = ''; Y.SEC.DEPO = ''; Y.OPT.SM.ID = ''; Y.CURR.AMT.BLOCKED = ''
	      Y.NEW.AMT.BLOCKED = ''; Y.EFF.FROM.DATE = ''; Y.BLOCKED.UNTIL = ''; Y.EFF.TO.DATE = ''; Y.ADDITION.INFO = ''
	      Y.LWM.SECTR.ID = ''; Y.RECORD.STATUS = ''; Y.INPUTTER = ''; Y.AUTHORISER = ''; Y.DATE.TIME = ''; Y.SC.BLK.SEC.POS.IDX = '' ; Y.PORTFOLIO.NO =''
	   
	      Y.SC.BLK.SEC.POS.IDX = Y.SC.BLK.SEC.POS.ID
		  Y.TXN.TYPE = R.SC.BLOCK.SEC.POS<SC.BSP.TRANSACTION.TYPE>
	      Y.BLOCK.TYPE = R.SC.BLOCK.SEC.POS<SC.BSP.LOCAL.REF,Y.L.BLK.TYPE.POS>
	      Y.SM.CODE = R.SC.BLOCK.SEC.POS<SC.BSP.SECURITY.CODE>
	      Y.SEC.DEPO = R.SC.BLOCK.SEC.POS<SC.BSP.SEC.DEPOT>
	      Y.OPT.SM.ID = R.SC.BLOCK.SEC.POS<SC.BSP.LOCAL.REF,Y.OPT.SM.ID.POS>
	      Y.CURR.AMT.BLOCKED = R.SC.BLOCK.SEC.POS<SC.BSP.CURR.AMT.BLOCKED>
	      Y.NEW.AMT.BLOCKED = R.SC.BLOCK.SEC.POS<SC.BSP.NEW.AMT.BLOCKED>
	      Y.EFF.FROM.DATE = R.SC.BLOCK.SEC.POS<SC.BSP.EFF.FROM.DATE>
	      Y.BLOCKED.UNTIL = R.SC.BLOCK.SEC.POS<SC.BSP.BLOCKED.UNTIL>
	      Y.EFF.TO.DATE = R.SC.BLOCK.SEC.POS<SC.BSP.EFF.TO.DATE>
	      Y.ADDITION.INFO = R.SC.BLOCK.SEC.POS<SC.BSP.ADDITION.INFO>
	      Y.LWM.SECTR.ID = R.SC.BLOCK.SEC.POS<SC.BSP.LOCAL.REF,Y.LWM.SECTR.ID.POS>
	      Y.RECORD.STATUS = R.SC.BLOCK.SEC.POS<SC.BSP.RECORD.STATUS>
	      Y.INPUTTER = R.SC.BLOCK.SEC.POS<SC.BSP.INPUTTER,1>
	      Y.AUTHORISER = R.SC.BLOCK.SEC.POS<SC.BSP.AUTHORISER,1>
	      Y.DATE.TIME = R.SC.BLOCK.SEC.POS<SC.BSP.DATE.TIME,1>	
 
**12911722-Start**
Y.PORTFOLIO.NO = R.SC.BLOCK.SEC.POS<SC.BSP.SECURITIES.ACCOUNT,1>
**12911722-End**
	      Y.ARRAY<-1> = Y.SC.BLK.SEC.POS.IDX:'*':Y.TXN.TYPE:'*':Y.BLOCK.TYPE:'*':Y.PORTFOLIO.NO:'*':Y.SM.CODE:'*':Y.SEC.DEPO:'*':Y.OPT.SM.ID:'*':Y.CURR.AMT.BLOCKED:'*':Y.NEW.AMT.BLOCKED:'*':Y.EFF.FROM.DATE:'*':Y.BLOCKED.UNTIL:'*':Y.EFF.TO.DATE:'*':Y.ADDITION.INFO:'*':Y.LWM.SECTR.ID:'*':Y.RECORD.STATUS:'*':Y.INPUTTER:'*':Y.AUTHORISER:'*':Y.DATE.TIME   

	   REPEAT
	      
	END

RETURN

END
