*-----------------------------------------------------------------------------
SUBROUTINE B.SCB.STMP.DTY.EXEMPT.LOAD
*-----------------------------------------------------------------------------
* Modification History :
*
* [Author] - [Date] - [ADO Ref] - LOAD for the Stamp Duty exemption extract batch.
*   Reads the exemption config (F.SCB.WM.H.LOCAL.PARAM 'STMP.DTY.EXEMPT.PARAM')
*   and opens all files used by SELECT / worker / POST.
*
* Called From:  BATCH>SNG/B.SCB.STMP.DTY.EXEMPT
*-----------------------------------------------------------------------------
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.SEC.TRADE
    $INSERT I_F.SECURITY.MASTER
    $INSERT I_F.SCB.WM.H.LOCAL.PARAM
    $INSERT I_B.SCB.STMP.DTY.EXEMPT.COMMON
*
    GOSUB INIT
RETURN
*=========
INIT:
*=========
    FN.SEC.TRADE = 'F.SEC.TRADE'
    F.SEC.TRADE = ''
    CALL OPF(FN.SEC.TRADE,F.SEC.TRADE)

    FN.SEC.TRADES.MDAY = 'F.SEC.TRADES.MDAY'
    F.SEC.TRADES.MDAY = ''
    CALL OPF(FN.SEC.TRADES.MDAY,F.SEC.TRADES.MDAY)

    FN.SCB.SEC.TRADES.LDAY = 'F.SCB.SEC.TRADES.LDAY'
    F.SCB.SEC.TRADES.LDAY = ''
    CALL OPF(FN.SCB.SEC.TRADES.LDAY,F.SCB.SEC.TRADES.LDAY)

    FN.SECURITY.MASTER = 'F.SECURITY.MASTER'
    F.SECURITY.MASTER = ''
    CALL OPF(FN.SECURITY.MASTER,F.SECURITY.MASTER)

    FN.SCB.WM.H.LOCAL.PARAM = 'F.SCB.WM.H.LOCAL.PARAM'
    F.SCB.WM.H.LOCAL.PARAM = ''
    CALL OPF(FN.SCB.WM.H.LOCAL.PARAM,F.SCB.WM.H.LOCAL.PARAM)

    FN.TEMP.STMP.DTY.EXEMPT = 'F.TEMP.STMP.DTY.EXEMPT'
    F.TEMP.STMP.DTY.EXEMPT = ''
    CALL OPF(FN.TEMP.STMP.DTY.EXEMPT,F.TEMP.STMP.DTY.EXEMPT)
*
    Y.RUN.DATE = TODAY
    Y.DATE.TODAY = OCONV(DATE(),"D4/")
    Y.RUN.CAL.DATE = Y.DATE.TODAY[7,4]:Y.DATE.TODAY[1,2]:Y.DATE.TODAY[4,2]
*
*   Read the configured exempt stock exchanges (values from config = single source)
*
    Y.SEHK.EXCHANGES = ''
    Y.LSE.EXCHANGES = ''
    CALL F.READ(FN.SCB.WM.H.LOCAL.PARAM,'STMP.DTY.EXEMPT.PARAM',R.SCB.WM.H.LOCAL.PARAM,F.SCB.WM.H.LOCAL.PARAM,LOCAL.ERR)
    Y.FIELD.NAMES = R.SCB.WM.H.LOCAL.PARAM<SCBWM.PRM.FIELD.NAME>
    LOCATE 'STMP.DTY.EXEMPT.STOCK.EXCHANGE.SEHK' IN Y.FIELD.NAMES<1,1> SETTING SEHK.POS THEN
        Y.SEHK.EXCHANGES = R.SCB.WM.H.LOCAL.PARAM<SCBWM.PRM.FIELD.VALUE,SEHK.POS>
        CONVERT @SM TO @VM IN Y.SEHK.EXCHANGES
    END
    LOCATE 'STMP.DTY.EXEMPT.STOCK.EXCHANGE.LSE' IN Y.FIELD.NAMES<1,1> SETTING LSE.POS THEN
        Y.LSE.EXCHANGES = R.SCB.WM.H.LOCAL.PARAM<SCBWM.PRM.FIELD.VALUE,LSE.POS>
        CONVERT @SM TO @VM IN Y.LSE.EXCHANGES
    END
*
    Y.RUN.DATE = TODAY
RETURN
END