* @ValidationCode : MjoxMDM3MTk5MTE6SVNPLTg4NTktMToxNzU5NDk2MjUwMzkyOjgyMjY2MDU6LTE6LTE6MDowOmZhbHNlOk4vQTpSMjBfU1AxMC4wOi0xOi0x
* @ValidationInfo : Timestamp         : 02 Jun 2026 18:27:30
* @ValidationInfo : Encoding          : ISO-8859-1
* @ValidationInfo : User Name         : 8226529
* @ValidationInfo : Nb tests success  : N/A
* @ValidationInfo : Nb tests failure  : N/A
* @ValidationInfo : Rating            : N/A
* @ValidationInfo : Coverage          : N/A
* @ValidationInfo : Strict flag       : N/A
* @ValidationInfo : Bypass GateKeeper : false
* @ValidationInfo : Compiler Version  : R20_SP10.0
SUBROUTINE SCB.EQD.NOF.ENQ.ST.GRP(FINAL.ARRAY)
*-----------------------------------------------------------------------------
*
*-----------------------------------------------------------------------------
* Modification History :
** 9th July 2026    12129747   Kavitha		- Enquiry to Display Aggregated Transfers along with their Corresponding Individual Trades
*-----------------------------------------------------------------------------
*Attached to ENQUIRY>SCB.ENQ.TRADE.GROUP, SS>NOFILE.SCB.ENQ.TRADE.GROUP
*-----------------------------------------------------------------------------
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_ENQUIRY.COMMON
    $INSERT I_F.SCB.PVB.EQD.GROUP.TODAY
    $INSERT I_F.SECURITY.TRANSFER
    $INSERT I_F.STOCK.EXCHANGE
	$INSERT I_F.DE.HEADER
	$INSERT I_F.SEC.TRADE
	$INSERT I_F.SECURITY.MASTER

    GOSUB INIT
    GOSUB SELECT.PROCESS

RETURN

INIT:
*****
    FN.SCB.PVB.EQD.GROUP.TODAY = 'F.SCB.PVB.EQD.GROUP.TODAY'
    F.SCB.PVB.EQD.GROUP.TODAY = ''
    CALL OPF(FN.SCB.PVB.EQD.GROUP.TODAY,F.SCB.PVB.EQD.GROUP.TODAY)
	
	FN.SECURITY.TRANSFER = 'F.SECURITY.TRANSFER'
	F.SECURITY.TRANSFER = ''
	CALL OPF(FN.SECURITY.TRANSFER,F.SECURITY.TRANSFER)
	
	FN.STOCK.EXCHANGE = 'F.STOCK.EXCHANGE'
	F.STOCK.EXCHANGE  = ''
	CALL OPF(FN.STOCK.EXCHANGE,F.STOCK.EXCHANGE)
	
	FN.DE.O.HEADER = 'F.DE.O.HEADER'	 	 	 
    F.DE.O.HEADER = ''	 	 	 
    CALL OPF('F.DE.O.HEADER',F.DE.O.HEADER)
	
	FN.SEC.TRADE = 'F.SEC.TRADE'
	F.SEC.TRADE = ''
	CALL OPF(FN.SEC.TRADE,F.SEC.TRADE)

       	FN.SEC.TRADE.HIS = 'F.SEC.TRADE$HIS'
	F.SEC.TRADE.HIS = ''
	CALL OPF(FN.SEC.TRADE.HIS,F.SEC.TRADE.HIS)

	
    FN.SECURITY.MASTER = 'F.SECURITY.MASTER'
	F.SECURITY.MASTER = ''
	CALL OPF(FN.SECURITY.MASTER,F.SECURITY.MASTER)
       LOC.REF.APP = 'SECURITY.TRANSFER'
       LOC.REF.FLD = '97A.SAFE.FIAC'
       LOC.REF.POS = ''
       CALL MULTI.GET.LOC.REF(LOC.REF.APP,LOC.REF.FLD,LOC.REF.POS)
       Y.LWM.POS = LOC.REF.POS<1,1>

RETURN

SELECT.PROCESS:
***************

    SEL.CMD = ''; SEL.LIST = ''; SEL.CNT = ''; SEL.ERR = ''; FINAL.ARRAY = ''; Y.ST.ID = ''; SEC.ERR = ''; SEL.FLD.POS = '';Y.DISPOSITION =''

    LOCATE 'TRADE.DATE' IN D.FIELDS<1> SETTING SEL.FLD.POS THEN
        ENQ.TRADE.DATE = D.RANGE.AND.VALUE<SEL.FLD.POS>
	SEL.CMD = 'SSELECT ':FN.SCB.PVB.EQD.GROUP.TODAY:' WITH TRADE.DATE EQ ':ENQ.TRADE.DATE:	
    END

      LOCATE 'DEPOSITORY' IN D.FIELDS<1> SETTING SEL.FLD.POS THEN
        E.GRP.ID = D.RANGE.AND.VALUE<SEL.FLD.POS>
		SEL.CMD := ' AND DEPO EQ ':E.GRP.ID
    END
			
    LOCATE 'Stk.Exch' IN D.FIELDS<1> SETTING SEL.FLD.POS THEN
        E.STK.EX = D.RANGE.AND.VALUE<SEL.FLD.POS>
        SEL.CMD := ' AND STOCK.EXCHANGE EQ ':E.STK.EX
    END
					
    LOCATE 'AUTHORISATION.DATE' IN D.FIELDS<1> SETTING SEL.FLD.POS THEN
        ENQ.AUTH.DATE = D.RANGE.AND.VALUE<SEL.FLD.POS>
        Y.OPER.VAL = D.LOGICAL.OPERANDS<SEL.FLD.POS>
            BEGIN CASE
        CASE Y.OPER.VAL = 1
            Y.OPER = 'EQ'
            SEL.CMD := ' AND AUTH.DATE EQ ':ENQ.AUTH.DATE
        CASE Y.OPER.VAL = 2
            Y.OPER = 'RG'
	CONVERT @SM TO @VM IN ENQ.AUTH.DATE
          
            SEL.CMD := ' AND AUTH.DATE ':"GE":' ':ENQ.AUTH.DATE<1,1>:' AND AUTH.DATE ':"LE":' ':ENQ.AUTH.DATE<1,2>
        END CASE            
    END		
    CALL EB.READLIST(SEL.CMD,SEL.LIST,'',SEL.CNT,SEL.ERR)

    LOOP
	
        REMOVE Y.ST.GRP.ID FROM SEL.LIST SETTING GRP.ID.POS
    WHILE Y.ST.GRP.ID : GRP.ID.POS
	
        R.SCB.PVB.EQD.GROUP.TODAY = '' ; ST.GRP.ERR = '' ; POS = ''
		Y.SEC.TRADE.ID.CNT = '' ; Y.VAL.DATE.CNT = '' ; Y.FT.IDS.CNT = ''
		
        CALL F.READ(FN.SCB.PVB.EQD.GROUP.TODAY,Y.ST.GRP.ID,R.SCB.PVB.EQD.GROUP.TODAY,F.SCB.PVB.EQD.GROUP.TODAY,ST.GRP.ERR)
        Y.STOCK.EXCHG = FIELD(Y.ST.GRP.ID,'.',6)
        Y.TRD.CCY = FIELD(Y.ST.GRP.ID,'.',5)
        Y.DEPO = FIELD(Y.ST.GRP.ID,'.',4)
		
        CALL F.READ(FN.STOCK.EXCHANGE,Y.STOCK.EXCHG,R.STOCK.EXCHANGE,F.STOCK.EXCHANGE,STOCK.EXCHANGE.ERR)
        IF R.STOCK.EXCHANGE THEN
            Y.STK.EXCH.DES = R.STOCK.EXCHANGE<SC.STE.DESCRIPTION,1>
        END
        Y.SEC.TFR.ERR = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.ERROR>
        Y.SEC.TRADE.ID = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID>
        Y.SEC.TFR.ID = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.TRANSFER.ID>
        Y.SEC.TFR.STATUS = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.STATUS>
        Y.SEC.TRADE.NOT.INC = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID.NOT.INCLUDED>
        Y.AUTH.DATE = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AUTH.DATE>
					
        GOSUB SEC.TFR.DETAILS
        Y.TOT.SEC.TRD.CNT = DCOUNT(Y.SEC.TRADE.ID,@VM)
					
        FOR K =1 TO Y.TOT.SEC.TRD.CNT

            Y.QTY = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.QUANTITY,K>
            Y.SEC.TRADE.ID = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID,K>
			GOSUB SEC.TRD.DETAILS
			Y.TRADE = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.TRADE.DATE,K>
			Y.VALUE = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.VALUE.DATE,K>
            Y.BR.GROSS.AMT.TRD = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.BR.GROSS.AMT.TRD,K>
            Y.BR.MISS.FEE = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.BR.MISC.FEE,K>	 
        	GOSUB WRITE.ARRAY
            Y.SEC.TFR.ID = ''; Y.NO.NOMINAL = ''; Y.BR.NET.AMT = '';Y.TRANSFER.CCY = '';Y.ACCOUNT = '';
        NEXT K
			
			 
        Y.TOT.SEC.TRD.NOT.INC.CNT = DCOUNT(Y.SEC.TRADE.NOT.INC ,@VM)
        FOR J =1 TO Y.TOT.SEC.TRD.NOT.INC.CNT
            Y.SEC.TFR.ID =  "Not Included"
            Y.QTY = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.QUANTITY.NOT.INCLUDED,J>
            Y.SEC.TRADE.ID = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID.NOT.INCLUDED,J>
			GOSUB SEC.TRD.DETAILS
			Y.TRADE = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.TRADE.DATE.NOT.INCLUDED,J>
			Y.VALUE = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.VALUE.DATE.NOT.INCLUDED,J>
            Y.BR.GROSS.AMT.TRD = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.BR.GROSS.AMT.TRD.NOT.INCLUDED,J>
            Y.BR.MISS.FEE = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.BR.MISC.FEE1.NOT.INCLUDED,J>
 
        	GOSUB WRITE.ARRAY
            Y.SEC.TFR.ID = ''; Y.ACCOUNT = '';
        NEXT J

    REPEAT
	
RETURN

SEC.TFR.DETAILS:
*****************
    IF Y.SEC.TFR.ID THEN
    CALL F.READ(FN.SECURITY.TRANSFER,Y.SEC.TFR.ID,R.SECURITY.TRANSFER,F.SECURITY.TRANSFER,SEC.ERR)

    Y.NO.NOMINAL = R.SECURITY.TRANSFER<SC.STR.NO.NOMINAL>
    Y.BR.NET.AMT = R.SECURITY.TRANSFER<SC.STR.BR.NET.AMT>
    Y.TRANSACTION.CODE  = R.SECURITY.TRANSFER<SC.STR.TRANSACTION.TYPE>
	Y.TRANSFER.CCY = R.SECURITY.TRANSFER<SC.STR.SECURITY.CCY>	
	Y.DELIVERY.REF = R.SECURITY.TRANSFER< SC.STR.DELIVERY.KEY>
    Y.ACCOUNT = R.SECURITY.TRANSFER<SC.STR.LOCAL.REF,Y.LWM.POS>	 
      	 	 	 
       IF Y.DELIVERY.REF THEN	 	 	 
       GOSUB GET.DELIVERY.DETAILS	 	 	 
       END
	
    END ELSE
     Y.TRANSFER.CCY = ''
     IF Y.SEC.TFR.ERR THEN
        Y.SEC.TFR.ID = " Transfer Not Created"
     END ELSE
        Y.SEC.TFR.ID = " Transfer Not Initiated"
     END
     END

RETURN

GET.DELIVERY.DETAILS:	 	 	 
*********************	 	 	 
 LOOP  	 	 	  
    REMOVE Y.DOH.ID FROM Y.DELIVERY.REF SETTING DOH.ID.POS		 	 
    WHILE Y.DOH.ID : DOH.ID.POS	 	 	 
    CALL F.READ(FN.DE.O.HEADER,Y.DOH.ID,R.DOH,F.DE.O.HEADER,DOH.READ.ERR)	 	 	 
    Y.MESSAGE.TYPE = R.DOH<DE.HDR.MESSAGE.TYPE>	 	 	 	 
 IF Y.MESSAGE.TYPE EQ "541" OR Y.MESSAGE.TYPE EQ "543" THEN	 	 	 
      Y.DISPOSITION =R.DOH<DE.HDR.MSG.DISP,1>	 	 	 
 END	 	 	  	 	 
 	 	 	 
 REPEAT	 	 	 
RETURN

SEC.TRD.DETAILS:
****************

    CALL F.READ(FN.SEC.TRADE,Y.SEC.TRADE.ID,R.SEC.TRADE,F.SEC.TRADE,SEC.TRD.ERR)
    IF SEC.TRD.ERR THEN
	Y.SEC.TRADE.ID.HIS = FIELD(Y.SEC.TRADE.ID,'-',1)
	                         
     CALL EB.READ.HISTORY.REC(F.SEC.TRADE.HIS,Y.SEC.TRADE.ID.HIS,R.SEC.TRADE,SEC.TRD.HIS.ERR)
    END
	Y.CUST.CODE = R.SEC.TRADE<SC.SBS.CUST.TRANS.CODE>	
	Y.SEC.CODE = R.SEC.TRADE<SC.SBS.SECURITY.CODE>	
	CALL F.READ(FN.SECURITY.MASTER,Y.SEC.CODE,R.SECURITY.MASTER,F.SECURITY.MASTER,SEC.MAS.ERR)
	Y.ISIN = R.SECURITY.MASTER<SC.SCM.I.S.I.N.>	
RETURN

WRITE.ARRAY:
************

    IF FINAL.ARRAY EQ '' THEN
        FINAL.ARRAY<-1> = Y.SEC.TFR.ID:'*':Y.NO.NOMINAL:'*':Y.TRANSFER.CCY:'*':Y.BR.NET.AMT:'*':Y.SEC.TRADE.ID:'*':Y.QTY:'*':Y.TRD.CCY:'*':Y.BR.GROSS.AMT.TRD:'*':Y.BR.MISS.FEE:'*':Y.STK.EXCH.DES:'*':Y.DEPO:'*':Y.TRADE:'*':Y.VALUE:'*':Y.CUST.CODE:'*':Y.ACCOUNT:'*':Y.ISIN :'*':Y.AUTH.DATE:'*':Y.SEC.TFR.STATUS:'*':Y.SEC.TFR.ERR:"*":Y.TRANSACTION.CODE:"*":Y.DISPOSITION
	END ELSE
        FINAL.ARRAY<-1> = Y.SEC.TFR.ID:'*':Y.NO.NOMINAL:'*':Y.TRANSFER.CCY:'*':Y.BR.NET.AMT:'*':Y.SEC.TRADE.ID:'*':Y.QTY:'*':Y.TRD.CCY:'*':Y.BR.GROSS.AMT.TRD:'*':Y.BR.MISS.FEE:'*':Y.STK.EXCH.DES:'*':Y.DEPO:'*':Y.TRADE:'*':Y.VALUE:'*':Y.CUST.CODE:'*':Y.ACCOUNT:'*':Y.ISIN :'*':Y.AUTH.DATE:'*':Y.SEC.TFR.STATUS:'*':Y.SEC.TFR.ERR:"*":Y.TRANSACTION.CODE:"*":Y.DISPOSITION
	END
*
RETURN
