SUBROUTINE B.SCB.PVB.EQD.AGGREGATED.TRANS(Y.GRP.ID)
*-----------------------------------------------------------------------------
* Record routine to create a aggregated transfer for the grouped trades.
* Author     - Raghavan K
* Date       - 26-Jun-2026
*-----------------------------------------------------------------------------
* Modification History :
*-----------------------------------------------------------------------------

*-----------------------------------------------------------------------------
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.SEC.TRADE
    $INSERT I_F.SCB.PVB.EQD.GROUP.TODAY
    $INSERT I_F.SECURITY.TRANSFER
    $INSERT I_B.SCB.PVB.EQD.AGGREGATED.TRANS.COMMON
    $INSERT I_F.SCB.WM.H.LOCAL.PARAM
    $INSERT I_F.SECURITY.MASTER
    $INSERT I_F.STOCK.EXCHANGE
    $INSERT I_F.SC.SETT.INSTRUCT
    $INSERT I_F.CUSTOMER.SECURITY
*
    GOSUB INITIALISE
    GOSUB START.TRACER
    GOSUB PROCESS
*
RETURN
*-----------
INITIALISE:
*----------
    R.SCB.PVB.EQD.GROUP.TODAY = '' ; Y.GROUP.TODAY.ERR = '' ;
    R.REC.SEC.CODE = '' ; ERR.SEC.CODE = '' ; R.STOCK.EXCHANGE   = '' ;  STOCK.EXCHANGE.ERR = '' ;
    Y.CUST.SEC.ERR = '' ; R.CUSTOMER.SECURITY = '' ; R.SEC.TRADE = '' ; ERR.SEC.TRADE = '' ;
    Y.TRADE.CUST = '' ; Y.BO.STATUS = '' ; Y.EQD.AGG.TXN = ''
*
RETURN
*-----------
PROCESS:
*----------
    CALL F.READ(FN.SCB.PVB.EQD.GROUP.TODAY,Y.GRP.ID,R.SCB.PVB.EQD.GROUP.TODAY,F.SCB.PVB.EQD.GROUP.TODAY,Y.GROUP.TODAY.ERR)
    Y.AGG.STATUS = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.STATUS>
    Y.AGG.TRANS.ID = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.TRANSFER.ID>
    IF R.SCB.PVB.EQD.GROUP.TODAY THEN
        GOSUB GET.GRP.CUST.DET
        GOSUB GET.SSI.DET
        GOSUB FORM.AGG.TRANS.OFS
    END
*
RETURN
*----------------
GET.GRP.CUST.DET:
*----------------
    Y.TRADE.ID = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID,1>
    CALL F.READ(FN.SEC.TRADE,Y.TRADE.ID,R.SEC.TRADE,F.SEC.TRADE,ERR.SEC.TRADE)
    Y.SECURITY.CODE = R.SEC.TRADE<SC.SBS.SECURITY.CODE>
    Y.DEPO = R.SEC.TRADE<SC.SBS.DEPOSITORY>
    Y.TRD.CCY = R.SEC.TRADE<SC.SBS.TRADE.CCY>
    Y.CUST.TRANS.CODE = R.SEC.TRADE<SC.SBS.CUST.TRANS.CODE,1>
    Y.TRADE.DATE = R.SEC.TRADE<SC.SBS.TRADE.DATE>
    Y.VALUE.DATE = R.SEC.TRADE<SC.SBS.VALUE.DATE>
    Y.REGION = ID.COMPANY[1,2]
    IF Y.REGION EQ 'SG' THEN
    	Y.CUSTOMER = Y.EQD.AGG.CUS.SG
    END ELSE
        Y.CUSTOMER = Y.EQD.AGG.CUS.HK
    END
    IF Y.CUST.TRANS.CODE EQ 'BUY' THEN
    	Y.EQD.AGG.TXN = Y.EQD.AGG.TXN.BUY
    END ELSE
	Y.EQD.AGG.TXN = Y.EQD.AGG.TXN.SELL
    END
    Y.NO.NOMINAL = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.QTY>
    Y.PRICE = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.PRICE,1>
    Y.STAMP.DUTY = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.STAMP.DUTY>
    Y.STOCK.EXCHG = R.SEC.TRADE<SC.SBS.STOCK.EXCHANGE>
    IF Y.STOCK.EXCHG EQ Y.EQD.AGG.STK.EXCH.SEHK AND Y.STAMP.DUTY GT 0 THEN
        Y.BO.STATUS = "CBO"
    END
RETURN
*------------
GET.SSI.DET:
*------------
    CALL F.READ(FN.SECURITY.MASTER,Y.SECURITY.CODE,R.REC.SEC.CODE,F.SECURITY.MASTER,ERR.SEC.CODE)
    IF R.REC.SEC.CODE THEN
    	Y.SECURITY.CURRENCY = R.REC.SEC.CODE<SC.SCM.SECURITY.CURRENCY>
    END
    CALL F.READ(FN.STOCK.EXCHANGE,Y.STOCK.EXCHG,R.STOCK.EXCHANGE,F.STOCK.EXCHANGE,STOCK.EXCHANGE.ERR)
    IF R.STOCK.EXCHANGE THEN
    	Y.STK.EXCH.MKTIDN = R.STOCK.EXCHANGE<SC.STE.MKT.IDN.CODE>
    END
*
    Y.SSI.ID = Y.DEPO:'*':Y.STOCK.EXCHG:'*':Y.SECURITY.CURRENCY
    R.SC.SETT.INSTRUCT = '' ; Y.SSI.ERR = ''
    CALL F.READ(FN.SC.SETT.INSTRUCT,Y.SSI.ID,R.SC.SETT.INSTRUCT,F.SC.SETT.INSTRUCT,Y.SSI.ERR)
    IF R.SC.SETT.INSTRUCT THEN
        IF Y.CUST.TRANS.CODE EQ 'BUY' THEN
            Y.LWM.95P.DEAG = R.SC.SETT.INSTRUCT<SC.SSI.LOCAL.REF,Y.LWM.SSI.95P.DEAG.POS>
            Y.95R.DEAG.REAG = R.SC.SETT.INSTRUCT<SC.SSI.DEAG,1>
            Y.LWM.TAG.95Q.DEA.REA = R.SC.SETT.INSTRUCT<SC.SSI.LOCAL.REF,Y.LWM.SSI.95Q.DEAG.POS>
            Y.97ASAFE.DEA.REA = R.SC.SETT.INSTRUCT<SC.SSI.DEAG.AC,1>
            Y.L.95R.BUYRSELL = R.SC.SETT.INSTRUCT<SC.SSI.SELL,1>
            Y.LWM.TAG.95P = R.SC.SETT.INSTRUCT<SC.SSI.LOCAL.REF,Y.SSI.SELL.95P.POS>
        END ELSE
            Y.LWM.95P.REAG = R.SC.SETT.INSTRUCT<SC.SSI.LOCAL.REF,Y.LWM.SSI.95P.REAG.POS>
            Y.95R.DEAG.REAG = R.SC.SETT.INSTRUCT<SC.SSI.REAG,1>
            Y.LWM.TAG.95Q.DEA.REA = R.SC.SETT.INSTRUCT<SC.SSI.LOCAL.REF,Y.LWM.SSI.95Q.REAG.POS>
            Y.97ASAFE.DEA.REA = R.SC.SETT.INSTRUCT<SC.SSI.REAG.AC,1>
            Y.L.95R.BUYRSELL = R.SC.SETT.INSTRUCT<SC.SSI.BUYR,1>
            Y.LWM.TAG.95P = R.SC.SETT.INSTRUCT<SC.SSI.LOCAL.REF,Y.SSI.BUYR.95P.POS>
        END
        Y.LWM.95P.PSET = R.SC.SETT.INSTRUCT<SC.SSI.PSET,1>
    END
    CALL F.READ(FN.CUSTOMER.SECURITY,Y.DEPO,R.CUSTOMER.SECURITY,F.CUSTOMER.SECURITY,Y.CUST.SEC.ERR)
    IF R.CUSTOMER.SECURITY THEN
*Omnibus and Segregated Safekeep account handling for SG Stocks in SG BC
        Y.TRADE.IDS = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID>
        Y.TRADE.CNT = DCOUNT(Y.TRADE.IDS,@VM)
        IF Y.STOCK.EXCHG EQ Y.EQD.AGG.STK.EXCH.SGX AND Y.TRD.CCY EQ 'SGD' AND Y.TRADE.CNT GT 1 THEN
            Y.97A.SAFE.FIAC = R.CUSTOMER.SECURITY<SC.CSC.SUB.ACC.EXT.ID,1>
        END ELSE
            Y.SUB.ACCOUNT = R.CUSTOMER.SECURITY<SC.CSC.SUB.ACCOUNT>
            Y.TRADE.CUST = R.SEC.TRADE<SC.SBS.CUSTOMER.NO>
            LOCATE Y.TRADE.CUST IN Y.SUB.ACCOUNT<1,1> SETTING Y.SUB.AC.POS THEN
            	Y.97A.SAFE.FIAC = R.CUSTOMER.SECURITY<SC.CSC.SUB.ACC.EXT.ID,Y.SUB.AC.POS>
            END ELSE
                Y.97A.SAFE.FIAC = R.CUSTOMER.SECURITY<SC.CSC.SUB.ACC.EXT.ID,1>
            END
        END
    END
*
    Y.STAMP.TXN.POS = ''; Y.SSI.STAMP.TXN = '';
    Y.SSI.STAMP.TXN = R.SC.SETT.INSTRUCT<SC.SSI.STAMP.TXN>
    LOCATE Y.EQD.AGG.TXN IN Y.SSI.STAMP.TXN<1,1,1> SETTING Y.STAMP.TXN.POS THEN
	Y.AT.STAMP.CODE.VAL = R.SC.SETT.INSTRUCT<SC.SSI.STAMP.INDICATOR,1,Y.STAMP.TXN.POS>
    END
*
    BEGIN CASE
        CASE Y.STOCK.EXCHG EQ Y.EQD.AGG.STK.EXCH.SEHK AND Y.STAMP.DUTY GT 0
            Y.AT.STAMP.CODE = Y.AT.STAMP.CODE.VAL
        CASE Y.STOCK.EXCHG EQ Y.EQD.AGG.STK.EXCH.LSE AND Y.STAMP.DUTY GT 0
            Y.AT.STAMP.CODE = Y.AT.STAMP.CODE.VAL
        CASE 1
            Y.AT.STAMP.CODE = ""
    END CASE
*
RETURN
*------------------
FORM.AGG.TRANS.OFS:
*------------------
*
    APP.NAME = 'SECURITY.TRANSFER'
    OFS.FUN = 'I'
    PROCESS = 'PROCESS'
    IF Y.CUST.TRANS.CODE EQ 'BUY' THEN
        OFS.VERSION = Y.EQD.AGG.VER.BUY
    END ELSE
        OFS.VERSION = Y.EQD.AGG.VER.SELL
    END
    GTSMODE = '1'
    NO.OF.AUTH = '0'
    TRANSACTION.ID = ''
    OFS.RECORD = ''
    Y.OFS.REC = ''
    Y.OFS.REC<SC.STR.SECURITY.NO> = Y.SECURITY.CODE
    Y.OFS.REC<SC.STR.DEPOSITORY> = Y.DEPO
    Y.OFS.REC<SC.STR.TRADE.DATE> = Y.TRADE.DATE
    Y.OFS.REC<SC.STR.VALUE.DATE> = Y.VALUE.DATE
    Y.OFS.REC<SC.STR.CUSTOMER.NO> = Y.CUSTOMER
    Y.OFS.REC<SC.STR.SECURITY.ACC> = Y.CUSTOMER:'-1'
    Y.OFS.REC< SC.STR.NO.NOMINAL> =  Y.NO.NOMINAL
    Y.OFS.REC<SC.STR.PRICE> = Y.PRICE
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.BO.STATUS.POS> = Y.BO.STATUS
    Y.OFS.REC<SC.STR.BROKER.NO> = Y.EQD.AGG.TRANS.BROKER
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.LWM.95P.DEAG.POS> = Y.LWM.95P.DEAG
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.97ASAFE.DEA.REA.POS> = Y.97ASAFE.DEA.REA
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.LWM.95P.REAG.POS> = Y.LWM.95P.REAG
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.95R.DEAG.REAG.POS> = Y.95R.DEAG.REAG
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.LWM.95P.PSET.BIC.POS> = Y.LWM.95P.PSET
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.AT.STAMP.CODE.POS> = Y.AT.STAMP.CODE
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.AT.TRAD.EXCH.POS> = Y.STK.EXCH.MKTIDN
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.LWM.TAG.95P.BUYSEL.BIC.POS> = Y.LWM.TAG.95P
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.L95R.BUYRSELL.POS> = Y.L.95R.BUYRSELL
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.LWM.ST.GRP.ID.POS> = Y.GRP.ID
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.95Q.DEAG.REAG.POS> = Y.LWM.TAG.95Q.DEA.REA
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.19A.STMP.DUTY.AMT.POS> = Y.STAMP.DUTY
    Y.OFS.REC<SC.STR.LOCAL.REF,Y.97A.SAFE.FIAC.POS> = Y.97A.SAFE.FIAC
    R.COMO<-1>="@01 Y.LWM.ST.GRP.ID : " : Y.GRP.ID
    R.COMO<-1>="@02 Y.97A.BUY.SEL.SAFE.AC.POS : ": Y.97A.BUY.SEL.SAFE.AC.POS
    R.COMO<-1>="@03 Y.BO.STATUS.POS : ": Y.BO.STATUS.POS
    R.COMO<-1>="@04 Y.LWM.95P.DEAG.POS : ": Y.LWM.95P.DEAG.POS
    R.COMO<-1>="@05 Y.97ASAFE.DEA.REA.POS : ": Y.97ASAFE.DEA.REA.POS
    R.COMO<-1>="@06 Y.LWM.95P.REAG.POS : ": Y.LWM.95P.REAG.POS
    R.COMO<-1>="@07 Y.95R.DEAG.REAG.POS : ": Y.95R.DEAG.REAG.POS
    R.COMO<-1>="@08 Y.LWM.95P.PSET.BIC.POS : ": Y.LWM.95P.PSET.BIC.POS
    R.COMO<-1>="@09 Y.AT.STAMP.CODE.POS : ": Y.AT.STAMP.CODE.POS
    R.COMO<-1>="@10 Y.AT.TRAD.EXCH.POS : ": Y.AT.TRAD.EXCH.POS
    R.COMO<-1>="@11 Y.LWM.TAG.95P.BUYSEL.BIC.POS : ": Y.LWM.TAG.95P.BUYSEL.BIC.POS
    R.COMO<-1>="@12 Y.L95R.BUYRSELL.POS : ": Y.L95R.BUYRSELL.POS
    R.COMO<-1>="@13 Y.LWM.ST.GRP.ID.POS : ": Y.LWM.ST.GRP.ID.POS
    R.COMO<-1>="@14 Y.95Q.DEAG.REAG.POS : ": Y.95Q.DEAG.REAG.POS
    R.COMO<-1>="@15 Y.19A.STMP.DUTY.AMT.POS : ": Y.19A.STMP.DUTY.AMT.POS    
    WRITE R.COMO TO F.COMO,COMO.ID 
*    
    CALL OFS.BUILD.RECORD(APP.NAME,OFS.FUN,PROCESS,OFS.VERSION,GTSMODE,NO.OF.AUTH,TRANSACTION.ID,Y.OFS.REC,OFS.RECORD)
    IF OFS.RECORD THEN
        Y.OFS.FLAG = ''; Y.OFS.OUT.MSG = '' ;
        CALL OFS.CALL.BULK.MANAGER(Y.EQD.AGG.OFS.SOURCE,OFS.RECORD,Y.OFS.OUT.MSG,Y.OFS.FLAG)
        Y.OFS.STATUS = '' ; Y.OUT.STATUS = ''
        Y.OFS.STATUS = FIELD(Y.OFS.OUT.MSG,',',1,1)
        Y.OUT.STATUS = FIELD(Y.OFS.STATUS,'/',3,1)
        IF Y.OUT.STATUS EQ '1' THEN
            GOSUB FORM.CONTRA.OFS.MSG
            GOSUB WRITE.TO.GROUPING.REF
        END ELSE
	    GOSUB WRITE.TO.GROUPING.REF
        END
    END
RETURN
*------------------
FORM.CONTRA.OFS.MSG:
*------------------
    CON.APP.NAME = 'SECURITY.TRANSFER'
    CON.OFS.FUN = 'I'
    CON.PROCESS = 'PROCESS'
    IF Y.CUST.TRANS.CODE EQ 'BUY' THEN
        CON.OFS.VERSION = Y.EQD.AGG.VER.SELL
    END ELSE
        CON.OFS.VERSION = Y.EQD.AGG.VER.BUY
    END
    CON.GTSMODE = '1'
    CON.NO.OF.AUTH = '0'
    Y.OFS.CONTRA.REC = ''
    CON.TRANSACTION.ID = ''
    Y.OFS.CONTRA.REC<SC.STR.SECURITY.NO> = Y.SECURITY.CODE
    Y.OFS.CONTRA.REC<SC.STR.DEPOSITORY> = Y.DEPO
    Y.OFS.CONTRA.REC<SC.STR.TRADE.DATE> = Y.TRADE.DATE
    Y.OFS.CONTRA.REC<SC.STR.VALUE.DATE> = Y.VALUE.DATE
    Y.OFS.CONTRA.REC<SC.STR.CUSTOMER.NO> = Y.CUSTOMER
    Y.OFS.CONTRA.REC<SC.STR.SECURITY.ACC> = Y.CUSTOMER:'-1'
    Y.OFS.CONTRA.REC< SC.STR.NO.NOMINAL> =  Y.NO.NOMINAL
    Y.OFS.CONTRA.REC<SC.STR.PRICE> = Y.PRICE
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.BO.STATUS.POS> = Y.BO.STATUS
    Y.OFS.CONTRA.REC<SC.STR.BROKER.NO> = Y.EQD.AGG.TRANS.BROKER
    Y.OFS.CONTRA.REC<SC.STR.PAYMENT.REQD> = 'NO'
    Y.OFS.CONTRA.REC<SC.STR.BROKER.ADVICE.REQD> = 'NO'
    Y.OFS.CONTRA.REC<SC.STR.DEPOT.ADVICE.REQD> = 'NO'
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.LWM.95P.DEAG.POS> = Y.LWM.95P.DEAG
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.97ASAFE.DEA.REA.POS> = Y.97ASAFE.DEA.REA
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.LWM.95P.REAG.POS> = Y.LWM.95P.REAG
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.95R.DEAG.REAG.POS> = Y.95R.DEAG.REAG
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.LWM.95P.PSET.BIC.POS> = Y.LWM.95P.PSET
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.AT.STAMP.CODE.POS> = Y.AT.STAMP.CODE
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.AT.TRAD.EXCH.POS> = Y.STK.EXCH.MKTIDN
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.LWM.TAG.95P.BUYSEL.BIC.POS> = Y.LWM.TAG.95P
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.L95R.BUYRSELL.POS> = Y.L.95R.BUYRSELL
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.LWM.ST.GRP.ID.POS> = 'CONTRA.':Y.GRP.ID
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.95Q.DEAG.REAG.POS> = Y.LWM.TAG.95Q.DEA.REA
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.19A.STMP.DUTY.AMT.POS> = Y.STAMP.DUTY
    Y.OFS.CONTRA.REC<SC.STR.LOCAL.REF,Y.97A.SAFE.FIAC.POS> = Y.97A.SAFE.FIAC
*
    CALL OFS.BUILD.RECORD(CON.APP.NAME,CON.OFS.FUN,CON.PROCESS,CON.OFS.VERSION,CON.GTSMODE,CON.NO.OF.AUTH,CON.TRANSACTION.ID,Y.OFS.CONTRA.REC,CON.OFS.RECORD)
    IF CON.OFS.RECORD THEN
        Y.CON.OFS.FLAG = ''; Y.CON.OFS.OUT.MSG = '' ;
        CALL OFS.CALL.BULK.MANAGER(Y.EQD.CON.AGG.OFS.SOURCE,CON.OFS.RECORD,Y.CON.OFS.OUT.MSG,Y.CON.OFS.FLAG)
    END
RETURN
*---------------------
WRITE.TO.GROUPING.REF:
*---------------------
    Y.TRANS.ID = '' ; Y.TRANS.STATUS = '' ; Y.CONTRA.TRANS.ERROR = '' ;
    Y.TRANS.ID = FIELD(FIELD(Y.OFS.OUT.MSG,',',1),'/',1)
    Y.TRANS.STATUS = FIELD(FIELD(Y.OFS.OUT.MSG,',',1),'/',3)
    IF Y.TRANS.STATUS EQ '1' THEN
        Y.TRANS.STATUS = 'LIVE'
	Y.CON.TRANS.STATUS = FIELD(FIELD(Y.CON.OFS.OUT.MSG,',',1),'/',3)
        IF Y.CON.TRANS.STATUS EQ '-1' THEN ;* Capture the error when Contra Agg Transfer getting failed.
	   Y.TRANS.STATUS = 'ERROR'
           Y.CONTRA.TRANS.ERROR = FIELD(Y.CON.OFS.OUT.MSG,',',2)
           Y.TRANS.ERROR = 'CONTRA-':Y.CONTRA.TRANS.ERROR 
           Y.TRANS.ID = ''
	END
    END ELSE
	Y.TRANS.STATUS = 'ERROR'
        Y.TRANS.ERROR = FIELD(Y.OFS.OUT.MSG,',',2)
        Y.TRANS.ID = ''
    END
    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.TRANSFER.ID>  = Y.TRANS.ID
    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.STATUS> = Y.TRANS.STATUS
    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.ERROR>  = Y.TRANS.ERROR
    CALL F.WRITE(FN.SCB.PVB.EQD.GROUP.TODAY,Y.GRP.ID,R.SCB.PVB.EQD.GROUP.TODAY)
*
RETURN
START.TRACER:
****************
    COMO.ID='B.SCB.PVB.EQD.AGGREGATED.TRANS':'#':TODAY:'#':TIME()
    R.COMO=''
    FN.COMO='&COMO&'
    R.COMO<-1>="@00 FN.COMO:":FN.COMO
    F.COMO=''
    CALL OPF(FN.COMO, F.COMO)
RETURN
END
