* @ValidationCode : Mjo4MzA1MTU0NDg6SVNPLTg4NTktMToxNzU2MzgzODA1MTM2OjgyMjY2MDU6LTE6LTE6MDowOmZhbHNlOk4vQTpSMjBfU1AxMC4wOi0xOi0x
* @ValidationInfo : Timestamp         : 28 Aug 2025 17:53:25
* @ValidationInfo : Encoding          : ISO-8859-1
* @ValidationInfo : User Name         : 8226605
* @ValidationInfo : Nb tests success  : N/A
* @ValidationInfo : Nb tests failure  : N/A
* @ValidationInfo : Rating            : N/A
* @ValidationInfo : Coverage          : N/A
* @ValidationInfo : Strict flag       : N/A
* @ValidationInfo : Bypass GateKeeper : false
* @ValidationInfo : Compiler Version  : R20_SP10.0
*-----------------------------------------------------------------------------
* <Rating>-30</Rating>
*-----------------------------------------------------------------------------
SUBROUTINE SCB.A.TRADE.EQD.GROUPING.UPD

*-----------------------------------------------------------------------------
* Modification History :
* 18/06/2026   12127880        8220461      Trade Grouping Logic in T24
*
* ----------------------------------------------------------------------------

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.SEC.TRADE
    $INSERT I_F.SCB.PVB.EQD.GROUP.TODAY
    $INSERT I_F.DATES
    $INSERT I_F.SECURITY.MASTER
    $INSERT I_F.CUSTOMER
	$INSERT I_F.SCB.WM.H.LOCAL.PARAM
*
   
	IF ID.COMPANY[1,2] NE "JE" THEN
       
        GOSUB OPEN.FILES
        GOSUB PROCESS
    END

RETURN

*==========
OPEN.FILES:
*===========

	Y.SECU.CODE = '' ;Y.STR.ID= '' ;R.REC.SEC.CODE =''
	
	FN.SCB.PVB.EQD.GROUP.TODAY = 'F.SCB.PVB.EQD.GROUP.TODAY'
	F.SCB.PVB.EQD.GROUP.TODAY = ''
	CALL OPF(FN.SCB.PVB.EQD.GROUP.TODAY,F.SCB.PVB.EQD.GROUP.TODAY)
	
	FN.SCB.WM.H.LOCAL.PARAM = 'F.SCB.WM.H.LOCAL.PARAM'
	F.SCB.WM.H.LOCAL.PARAM = ''
	CALL OPF(FN.SCB.WM.H.LOCAL.PARAM,F.SCB.WM.H.LOCAL.PARAM)
			
	FN.SECURITY.MASTER = 'F.SECURITY.MASTER'
	F.SECURITY.MASTER  = ''
	CALL OPF(FN.SECURITY.MASTER,F.SECURITY.MASTER)

	FN.CUSTOMER = 'F.CUSTOMER'
	F.CUSTOMER = ''
	CALL OPF(FN.CUSTOMER,F.CUSTOMER)

    Y.LWM.PVB.INDICATOR = '';Y.PVB.CUS.FLAG = ''
	Y.SECU.CODE = R.NEW(SC.SBS.SECURITY.CODE)
	CALL F.READ(FN.SECURITY.MASTER,Y.SECU.CODE,R.REC.SEC.CODE,F.SECURITY.MASTER,ERR.SEC.CODE)
	Y.SAT.CODE.SEC = R.REC.SEC.CODE<SC.SCM.SUB.ASSET.TYPE>
	
    Y.APPLICATION = 'SEC.TRADE' :@FM: 'CUSTOMER'
    Y.FLD = 'LWM.ST.GRP.ID':@VM:'LWM.PVB.IND':@VM:'LED.TICKET.TYPE':@FM:'L.O.B'
    Y.LOC.POS = ''
    CALL MULTI.GET.LOC.REF(Y.APPLICATION,Y.FLD,Y.LOC.POS)
    Y.ST.GRP.ID.POS   = Y.LOC.POS<1,1>
    Y.PVB.IND.POS   = Y.LOC.POS<1,2>
    LED.TICKET.TYPE.POS = Y.LOC.POS<1,3>
	LOB.POS       = Y.LOC.POS<2,1>
	

RETURN
*=========
PROCESS:
*========
   
    Y.ST.CNT = ''
    R.SCB.PVB.EQD.GROUP.TODAY =''; Y.GRP.ID = ''
    Y.ST.LED.TICKET.TYPE = R.NEW(SC.SBS.LOCAL.REF)<1,LED.TICKET.TYPE.POS>
    BEGIN CASE
        CASE R.NEW(SC.SBS.RECORD.STATUS)[1,4] EQ "INAU"
            GOSUB GROUP.ID.FORMATION
            IF Y.FLAG.LED.TICKET.TYPE EQ '1' AND (Y.SAT.CODE.FLAG EQ '1') AND (Y.PVB.CUS.FLAG EQ '1') THEN
                        				
                IF NOT(Y.STR.ID) THEN
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID,-1>     = ID.NEW
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.QUANTITY,-1> = R.NEW(SC.SBS.BR.NO.NOM)
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.PRICE,-1>   = R.NEW(SC.SBS.BR.PRICE)
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.TRADE.DATE,-1> = R.NEW(SC.SBS.TRADE.DATE)
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.VALUE.DATE,-1> = R.NEW(SC.SBS.VALUE.DATE)
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.CUS.TRANS.CODE,-1> = R.NEW(SC.SBS.CUST.TRANS.CODE)
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.BR.GROSS.AMT.TRD,-1> = R.NEW(SC.SBS.BR.GROSS.AM.TRD)
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.BR.MISC.FEE,-1> = R.NEW(SC.SBS.BR.FEES.MISC)
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AUTH.DATE> = Y.CAL.DATE
					 R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.DEPO,-1> = Y.DEPO	
					 R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.STOCK.EXCHANGE,-1> = Y.STK.EXCH
					 GOSUB UPDATE.AGG.QTY
                END ELSE
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID.NOT.INCLUDED,-1>     = ID.NEW
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.QUANTITY.NOT.INCLUDED,-1> = R.NEW(SC.SBS.BR.NO.NOM)
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.PRICE.NOT.INCLUDED,-1>   = R.NEW(SC.SBS.BR.PRICE)
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.TRADE.DATE.NOT.INCLUDED,-1> = R.NEW(SC.SBS.TRADE.DATE)
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.VALUE.DATE.NOT.INCLUDED,-1> = R.NEW(SC.SBS.VALUE.DATE)
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.CUST.TRANS.CODE.NOT.INCLUDED,-1> = R.NEW(SC.SBS.CUST.TRANS.CODE)
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.BR.GROSS.AMT.TRD.NOT.INCLUDED,-1> = R.NEW(SC.SBS.BR.GROSS.AM.TRD)
                    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.BR.MISC.FEE1.NOT.INCLUDED,-1> = R.NEW(SC.SBS.BR.FEES.MISC)
					R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.STOCK.EXCHANGE.NOT.INCLUDED,-1> = Y.STK.EXCH
					R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.DEPO.NOT.INCLUDED,-1> = Y.DEPO
					
                                           
                END
               
		
                CALL F.WRITE(FN.SCB.PVB.EQD.GROUP.TODAY,Y.GRP.ID,R.SCB.PVB.EQD.GROUP.TODAY)
                R.NEW(SC.SBS.LOCAL.REF)<1,Y.ST.GRP.ID.POS> = Y.GRP.ID
        
            END
        CASE R.NEW(SC.SBS.RECORD.STATUS)[1,4] EQ "RNAU"
            Y.GRP.ID = R.NEW(SC.SBS.LOCAL.REF)<1,Y.ST.GRP.ID.POS>
		
            CALL F.READU(FN.SCB.PVB.EQD.GROUP.TODAY,Y.GRP.ID,R.SCB.PVB.EQD.GROUP.TODAY,F.SCB.PVB.EQD.GROUP.TODAY,ERR.ST.FND,'')
            IF R.SCB.PVB.EQD.GROUP.TODAY THEN
 
                FINDSTR ID.NEW IN R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID> SETTING POS.FM, POS.VM THEN
				    Y.STR.ID = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.TRANSFER.ID>
                    Y.ST.ID = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID>
                    IF Y.STR.ID THEN
                        R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID,POS.VM> = ID.NEW:'-R'
                        CALL F.WRITE(FN.SCB.PVB.EQD.GROUP.TODAY,Y.GRP.ID,R.SCB.PVB.EQD.GROUP.TODAY)
                    END ELSE
				
                        Y.ST.CNT = DCOUNT(Y.ST.ID,@VM)
					
                        IF Y.ST.CNT EQ 1 THEN
                            CALL F.DELETE(FN.SCB.PVB.EQD.GROUP.TODAY,Y.GRP.ID)
			    R.NEW(SC.SBS.LOCAL.REF)<1,Y.ST.GRP.ID.POS> = ''
                        END ELSE
					
                            DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID,POS.VM>
                            DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.QUANTITY,POS.VM>
                            DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.PRICE,POS.VM>
                            DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.TRADE.DATE,POS.VM>
                            DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.VALUE.DATE,POS.VM>
                            DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.CUS.TRANS.CODE,POS.VM>
                            DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.BR.GROSS.AMT.TRD,POS.VM>
                            DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.BR.MISC.FEE,POS.VM>
							DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.DEPO,POS.VM> 
					        DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.STOCK.EXCHANGE,POS.VM>
							
							
					
                            Y.BR.FEE.MISC = R.NEW(SC.SBS.BR.FEES.MISC)
	
                            IF Y.STK.EXCH EQ "104" THEN
                                Y.BR.FEE.MISC = Y.BR.FEE.MISC*2
                            END
					
					
                            R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.QTY> = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.QTY> - R.NEW(SC.SBS.BR.NO.NOM)
                            R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.STAMP.DUTY> = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.STAMP.DUTY> - Y.BR.FEE.MISC
                            Y.AGG.QTY = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.QTY>
                            Y.STP =R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.STAMP.DUTY>
                            CALL F.WRITE(FN.SCB.PVB.EQD.GROUP.TODAY,Y.GRP.ID,R.SCB.PVB.EQD.GROUP.TODAY)
                        END
                    END
				
                    R.NEW(SC.SBS.LOCAL.REF)<1,Y.ST.GRP.ID.POS> = ''
			
                END
                FINDSTR ID.NEW IN R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID.NOT.INCLUDED> SETTING SEC.POS.FM, SEC.POS.VM THEN
                    DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.SEC.TRADE.ID.NOT.INCLUDED,SEC.POS.VM>
                    DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.QUANTITY.NOT.INCLUDED,SEC.POS.VM>
                    DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.PRICE.NOT.INCLUDED,SEC.POS.VM>
                    DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.TRADE.DATE.NOT.INCLUDED,SEC.POS.VM>
                    DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.VALUE.DATE.NOT.INCLUDED,SEC.POS.VM>
                    DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.CUST.TRANS.CODE.NOT.INCLUDED,SEC.POS.VM>
                    DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.BR.GROSS.AMT.TRD.NOT.INCLUDED,SEC.POS.VM>
                    DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.BR.MISC.FEE1.NOT.INCLUDED,SEC.POS.VM>
					DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.STOCK.EXCHANGE.NOT.INCLUDED,SEC.POS.VM>
					DEL R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.DEPO.NOT.INCLUDED,SEC.POS.VM> 
					CALL F.WRITE(FN.SCB.PVB.EQD.GROUP.TODAY,Y.GRP.ID,R.SCB.PVB.EQD.GROUP.TODAY)                    
                END
                
            END
        
    END CASE
    CALL F.RELEASE(FN.SCB.PVB.EQD.GROUP.TODAY,Y.GRP.ID,R.SCB.PVB.EQD.GROUP.TODAY)
   
RETURN

*================
GROUP.ID.FORMATION:
*==================
    GRP.ID = ''; Y.GRP.ID = ''
	R.SCB.PVB.EQD.GROUP.TODAY= ''
	
    GOSUB LED.TICKET.TYPE
    GOSUB CHK.PVB.CUSTOMER
	
	Y.SEC.CODE = R.NEW(SC.SBS.SECURITY.CODE)
	Y.DEPO = R.NEW(SC.SBS.DEPOSITORY)
	Y.TRD.CCY = R.NEW(SC.SBS.TRADE.CCY)
	Y.STK.EXCH =R.NEW(SC.SBS.STOCK.EXCHANGE)
	Y.TRANS.CODE = R.NEW(SC.SBS.CUST.TRANS.CODE)
	Y.CUST.PRICE = R.NEW(SC.SBS.CUST.PRICE)
	Y.TRD.DATE = R.NEW(SC.SBS.TRADE.DATE)
	Y.VALUE.DATE =R.NEW(SC.SBS.VALUE.DATE)
	
	GRP.ID = Y.SEC.CODE:".":Y.DEPO:".":Y.TRD.CCY:".":Y.STK.EXCH:".":Y.TRANS.CODE:".":Y.CUST.PRICE:".":Y.TRD.DATE:".":Y.VALUE.DATE
	Y.DATE.TODAY = OCONV(DATE(),"D4/")
    Y.CAL.DATE = Y.DATE.TODAY[7,4]:Y.DATE.TODAY[1,2]:Y.DATE.TODAY[4,2]
	    
	Y.LWM.PVB.INDICATOR = R.NEW(SC.SBS.LOCAL.REF)<1,Y.PVB.IND.POS>
    Y.GRP.ID = "EQD":".":Y.LWM.PVB.INDICATOR:".":GRP.ID:".":Y.CAL.DATE

    CALL F.READU(FN.SCB.PVB.EQD.GROUP.TODAY,Y.GRP.ID,R.SCB.PVB.EQD.GROUP.TODAY,F.SCB.PVB.EQD.GROUP.TODAY,ERR.ST.FND,'')
	
    Y.STR.ID = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.TRANSFER.ID>

RETURN

*==============
UPDATE.AGG.QTY:
*==============
    Y.QTY = '' ; Y.MISC.FEE =''
    Y.QTY = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.QTY>
    Y.MISC.FEE = R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.STAMP.DUTY>
	
	Y.BR.FEE.MISC = R.NEW(SC.SBS.BR.FEES.MISC)
	
    IF Y.STK.EXCH EQ "104" THEN
        Y.BR.FEE.MISC = Y.BR.FEE.MISC*2
	END
	   
    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.QTY> = Y.QTY + R.NEW(SC.SBS.BR.NO.NOM)
    R.SCB.PVB.EQD.GROUP.TODAY<SCB.EQD.ST.AGGREGATED.STAMP.DUTY> = Y.MISC.FEE + Y.BR.FEE.MISC

     

RETURN

*===============
LED.TICKET.TYPE:
*===============
    R.SCB.WM.H.LOCAL.PARAM = ''
    CALL F.READ(FN.SCB.WM.H.LOCAL.PARAM,'EQD.STAMP.FUNDING.WITHDRAWAL',R.SCB.WM.H.LOCAL.PARAM,F.SCB.WM.H.LOCAL.PARAM,ERR.LOC.PARA)
    Y.FIELD.NAMES = R.SCB.WM.H.LOCAL.PARAM<SCBWM.PRM.FIELD.NAME>
    Y.FLAG.LED.TICKET.TYPE = ''
    LOCATE 'EQD.LED.TICKET.TYPE' IN Y.FIELD.NAMES<1,1> SETTING FI.VER.POS THEN
        Y.LED.TICKET.TYPE = R.SCB.WM.H.LOCAL.PARAM<SCBWM.PRM.FIELD.VALUE,FI.VER.POS>
        LOCATE Y.ST.LED.TICKET.TYPE IN Y.LED.TICKET.TYPE<1,1,1> SETTING LED.TKT.POS THEN
            Y.FLAG.LED.TICKET.TYPE = '1'
        END

    END
*
    Y.SAT.CODE.FLAG = '' ; Y.SAT.POS = ''
    LOCATE 'EQD.SAT.CODES'IN Y.FIELD.NAMES<1,1> SETTING Y.SAT.POS THEN
        Y.SAT.CODES = R.SCB.WM.H.LOCAL.PARAM<SCBWM.PRM.FIELD.VALUE,Y.SAT.POS>
        CONVERT @SM TO @VM IN Y.SAT.CODES
        IF Y.SAT.CODE.SEC MATCHES Y.SAT.CODES THEN
            Y.SAT.CODE.FLAG = '1'
        END
	
    END
    

RETURN

*=================
CHK.PVB.CUSTOMER:
*=================
    R.REC.CUST = ''
    Y.CUST.NO = R.NEW(SC.SBS.CUSTOMER.NO)
	Y.PVB.CUS.FLAG = '1'
    IF ID.COMPANY[1,2] EQ "SG" THEN
        Y.PARAM.ID =''; Y.ALLOW.SEG ='PVB'; Y.ALLOWED.LOB =''
        CALL SCB.GET.ALLOWED.CUST.SEG(Y.PARAM.ID,Y.ALLOW.SEG,Y.ALLOWED.LOB)
	
        CALL F.READ(FN.CUSTOMER,Y.CUST.NO,R.REC.CUST,F.CUSTOMER,ERR.CUSTOMER)
        Y.LOB.CUS = R.REC.CUST<EB.CUS.LOCAL.REF,LOB.POS>
	
        IF Y.LOB.CUS MATCHES Y.ALLOWED.LOB THEN
            Y.PVB.CUS.FLAG = '1'
        END ELSE
            Y.PVB.CUS.FLAG = ''
        END
    END

RETURN

END
